// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	workflow "mini-workflow/api"
)

// MockMatchingService is an autogenerated mock type for the MatchingService type
type MockMatchingService struct {
	mock.Mock
}

type MockMatchingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchingService) EXPECT() *MockMatchingService_Expecter {
	return &MockMatchingService_Expecter{mock: &_m.Mock}
}

// AddActivityTask provides a mock function with given fields: ctx, req
func (_m *MockMatchingService) AddActivityTask(ctx context.Context, req *workflow.AddActivityTaskRequest) (*workflow.AddActivityTaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddActivityTask")
	}

	var r0 *workflow.AddActivityTaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddActivityTaskRequest) (*workflow.AddActivityTaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddActivityTaskRequest) *workflow.AddActivityTaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.AddActivityTaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.AddActivityTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingService_AddActivityTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddActivityTask'
type MockMatchingService_AddActivityTask_Call struct {
	*mock.Call
}

// AddActivityTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.AddActivityTaskRequest
func (_e *MockMatchingService_Expecter) AddActivityTask(ctx interface{}, req interface{}) *MockMatchingService_AddActivityTask_Call {
	return &MockMatchingService_AddActivityTask_Call{Call: _e.mock.On("AddActivityTask", ctx, req)}
}

func (_c *MockMatchingService_AddActivityTask_Call) Run(run func(ctx context.Context, req *workflow.AddActivityTaskRequest)) *MockMatchingService_AddActivityTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.AddActivityTaskRequest))
	})
	return _c
}

func (_c *MockMatchingService_AddActivityTask_Call) Return(_a0 *workflow.AddActivityTaskResponse, _a1 error) *MockMatchingService_AddActivityTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingService_AddActivityTask_Call) RunAndReturn(run func(context.Context, *workflow.AddActivityTaskRequest) (*workflow.AddActivityTaskResponse, error)) *MockMatchingService_AddActivityTask_Call {
	_c.Call.Return(run)
	return _c
}

// AddWorkflowTask provides a mock function with given fields: ctx, req
func (_m *MockMatchingService) AddWorkflowTask(ctx context.Context, req *workflow.AddWorkflowTaskRequest) (*workflow.AddWorkflowTaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkflowTask")
	}

	var r0 *workflow.AddWorkflowTaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddWorkflowTaskRequest) (*workflow.AddWorkflowTaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddWorkflowTaskRequest) *workflow.AddWorkflowTaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.AddWorkflowTaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.AddWorkflowTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingService_AddWorkflowTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkflowTask'
type MockMatchingService_AddWorkflowTask_Call struct {
	*mock.Call
}

// AddWorkflowTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.AddWorkflowTaskRequest
func (_e *MockMatchingService_Expecter) AddWorkflowTask(ctx interface{}, req interface{}) *MockMatchingService_AddWorkflowTask_Call {
	return &MockMatchingService_AddWorkflowTask_Call{Call: _e.mock.On("AddWorkflowTask", ctx, req)}
}

func (_c *MockMatchingService_AddWorkflowTask_Call) Run(run func(ctx context.Context, req *workflow.AddWorkflowTaskRequest)) *MockMatchingService_AddWorkflowTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.AddWorkflowTaskRequest))
	})
	return _c
}

func (_c *MockMatchingService_AddWorkflowTask_Call) Return(_a0 *workflow.AddWorkflowTaskResponse, _a1 error) *MockMatchingService_AddWorkflowTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingService_AddWorkflowTask_Call) RunAndReturn(run func(context.Context, *workflow.AddWorkflowTaskRequest) (*workflow.AddWorkflowTaskResponse, error)) *MockMatchingService_AddWorkflowTask_Call {
	_c.Call.Return(run)
	return _c
}

// PollActivityTaskQueue provides a mock function with given fields: ctx, req
func (_m *MockMatchingService) PollActivityTaskQueue(ctx context.Context, req *workflow.PollActivityTaskQueueRequest) (*workflow.PollActivityTaskQueueResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PollActivityTaskQueue")
	}

	var r0 *workflow.PollActivityTaskQueueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.PollActivityTaskQueueRequest) (*workflow.PollActivityTaskQueueResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.PollActivityTaskQueueRequest) *workflow.PollActivityTaskQueueResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.PollActivityTaskQueueResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.PollActivityTaskQueueRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingService_PollActivityTaskQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollActivityTaskQueue'
type MockMatchingService_PollActivityTaskQueue_Call struct {
	*mock.Call
}

// PollActivityTaskQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.PollActivityTaskQueueRequest
func (_e *MockMatchingService_Expecter) PollActivityTaskQueue(ctx interface{}, req interface{}) *MockMatchingService_PollActivityTaskQueue_Call {
	return &MockMatchingService_PollActivityTaskQueue_Call{Call: _e.mock.On("PollActivityTaskQueue", ctx, req)}
}

func (_c *MockMatchingService_PollActivityTaskQueue_Call) Run(run func(ctx context.Context, req *workflow.PollActivityTaskQueueRequest)) *MockMatchingService_PollActivityTaskQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.PollActivityTaskQueueRequest))
	})
	return _c
}

func (_c *MockMatchingService_PollActivityTaskQueue_Call) Return(_a0 *workflow.PollActivityTaskQueueResponse, _a1 error) *MockMatchingService_PollActivityTaskQueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingService_PollActivityTaskQueue_Call) RunAndReturn(run func(context.Context, *workflow.PollActivityTaskQueueRequest) (*workflow.PollActivityTaskQueueResponse, error)) *MockMatchingService_PollActivityTaskQueue_Call {
	_c.Call.Return(run)
	return _c
}

// PollWorkflowTaskQueue provides a mock function with given fields: ctx, req
func (_m *MockMatchingService) PollWorkflowTaskQueue(ctx context.Context, req *workflow.PollWorkflowTaskQueueRequest) (*workflow.PollWorkflowTaskQueueResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PollWorkflowTaskQueue")
	}

	var r0 *workflow.PollWorkflowTaskQueueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.PollWorkflowTaskQueueRequest) (*workflow.PollWorkflowTaskQueueResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.PollWorkflowTaskQueueRequest) *workflow.PollWorkflowTaskQueueResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.PollWorkflowTaskQueueResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.PollWorkflowTaskQueueRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingService_PollWorkflowTaskQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollWorkflowTaskQueue'
type MockMatchingService_PollWorkflowTaskQueue_Call struct {
	*mock.Call
}

// PollWorkflowTaskQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.PollWorkflowTaskQueueRequest
func (_e *MockMatchingService_Expecter) PollWorkflowTaskQueue(ctx interface{}, req interface{}) *MockMatchingService_PollWorkflowTaskQueue_Call {
	return &MockMatchingService_PollWorkflowTaskQueue_Call{Call: _e.mock.On("PollWorkflowTaskQueue", ctx, req)}
}

func (_c *MockMatchingService_PollWorkflowTaskQueue_Call) Run(run func(ctx context.Context, req *workflow.PollWorkflowTaskQueueRequest)) *MockMatchingService_PollWorkflowTaskQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.PollWorkflowTaskQueueRequest))
	})
	return _c
}

func (_c *MockMatchingService_PollWorkflowTaskQueue_Call) Return(_a0 *workflow.PollWorkflowTaskQueueResponse, _a1 error) *MockMatchingService_PollWorkflowTaskQueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingService_PollWorkflowTaskQueue_Call) RunAndReturn(run func(context.Context, *workflow.PollWorkflowTaskQueueRequest) (*workflow.PollWorkflowTaskQueueResponse, error)) *MockMatchingService_PollWorkflowTaskQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchingService creates a new instance of MockMatchingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchingService {
	mock := &MockMatchingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
