// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskQueue is an autogenerated mock type for the TaskQueue type
type MockTaskQueue struct {
	mock.Mock
}

type MockTaskQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskQueue) EXPECT() *MockTaskQueue_Expecter {
	return &MockTaskQueue_Expecter{mock: &_m.Mock}
}

// BlockPop provides a mock function with given fields: ctx, key, timeoutSecs
func (_m *MockTaskQueue) BlockPop(ctx context.Context, key string, timeoutSecs int) ([]byte, error) {
	ret := _m.Called(ctx, key, timeoutSecs)

	if len(ret) == 0 {
		panic("no return value specified for BlockPop")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]byte, error)); ok {
		return rf(ctx, key, timeoutSecs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []byte); ok {
		r0 = rf(ctx, key, timeoutSecs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, key, timeoutSecs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskQueue_BlockPop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockPop'
type MockTaskQueue_BlockPop_Call struct {
	*mock.Call
}

// BlockPop is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - timeoutSecs int
func (_e *MockTaskQueue_Expecter) BlockPop(ctx interface{}, key interface{}, timeoutSecs interface{}) *MockTaskQueue_BlockPop_Call {
	return &MockTaskQueue_BlockPop_Call{Call: _e.mock.On("BlockPop", ctx, key, timeoutSecs)}
}

func (_c *MockTaskQueue_BlockPop_Call) Run(run func(ctx context.Context, key string, timeoutSecs int)) *MockTaskQueue_BlockPop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockTaskQueue_BlockPop_Call) Return(_a0 []byte, _a1 error) *MockTaskQueue_BlockPop_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskQueue_BlockPop_Call) RunAndReturn(run func(context.Context, string, int) ([]byte, error)) *MockTaskQueue_BlockPop_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: ctx, key, payload
func (_m *MockTaskQueue) Push(ctx context.Context, key string, payload []byte) error {
	ret := _m.Called(ctx, key, payload)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, key, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskQueue_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockTaskQueue_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - payload []byte
func (_e *MockTaskQueue_Expecter) Push(ctx interface{}, key interface{}, payload interface{}) *MockTaskQueue_Push_Call {
	return &MockTaskQueue_Push_Call{Call: _e.mock.On("Push", ctx, key, payload)}
}

func (_c *MockTaskQueue_Push_Call) Run(run func(ctx context.Context, key string, payload []byte)) *MockTaskQueue_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockTaskQueue_Push_Call) Return(_a0 error) *MockTaskQueue_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskQueue_Push_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockTaskQueue_Push_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskQueue creates a new instance of MockTaskQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskQueue {
	mock := &MockTaskQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
