// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "mini-workflow/history/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockTimerStore is an autogenerated mock type for the TimerStore type
type MockTimerStore struct {
	mock.Mock
}

type MockTimerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTimerStore) EXPECT() *MockTimerStore_Expecter {
	return &MockTimerStore_Expecter{mock: &_m.Mock}
}

// ClaimExpired provides a mock function with given fields: ctx, nowMs, batchSize
func (_m *MockTimerStore) ClaimExpired(ctx context.Context, nowMs int64, batchSize int) ([]string, error) {
	ret := _m.Called(ctx, nowMs, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for ClaimExpired")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) ([]string, error)); ok {
		return rf(ctx, nowMs, batchSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) []string); ok {
		r0 = rf(ctx, nowMs, batchSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = rf(ctx, nowMs, batchSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTimerStore_ClaimExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimExpired'
type MockTimerStore_ClaimExpired_Call struct {
	*mock.Call
}

// ClaimExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - nowMs int64
//   - batchSize int
func (_e *MockTimerStore_Expecter) ClaimExpired(ctx interface{}, nowMs interface{}, batchSize interface{}) *MockTimerStore_ClaimExpired_Call {
	return &MockTimerStore_ClaimExpired_Call{Call: _e.mock.On("ClaimExpired", ctx, nowMs, batchSize)}
}

func (_c *MockTimerStore_ClaimExpired_Call) Run(run func(ctx context.Context, nowMs int64, batchSize int)) *MockTimerStore_ClaimExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int))
	})
	return _c
}

func (_c *MockTimerStore_ClaimExpired_Call) Return(_a0 []string, _a1 error) *MockTimerStore_ClaimExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTimerStore_ClaimExpired_Call) RunAndReturn(run func(context.Context, int64, int) ([]string, error)) *MockTimerStore_ClaimExpired_Call {
	_c.Call.Return(run)
	return _c
}

// RebuildFromDB provides a mock function with given fields: ctx, timers
func (_m *MockTimerStore) RebuildFromDB(ctx context.Context, timers []domain.Timer) error {
	ret := _m.Called(ctx, timers)

	if len(ret) == 0 {
		panic("no return value specified for RebuildFromDB")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Timer) error); ok {
		r0 = rf(ctx, timers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTimerStore_RebuildFromDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebuildFromDB'
type MockTimerStore_RebuildFromDB_Call struct {
	*mock.Call
}

// RebuildFromDB is a helper method to define mock.On call
//   - ctx context.Context
//   - timers []domain.Timer
func (_e *MockTimerStore_Expecter) RebuildFromDB(ctx interface{}, timers interface{}) *MockTimerStore_RebuildFromDB_Call {
	return &MockTimerStore_RebuildFromDB_Call{Call: _e.mock.On("RebuildFromDB", ctx, timers)}
}

func (_c *MockTimerStore_RebuildFromDB_Call) Run(run func(ctx context.Context, timers []domain.Timer)) *MockTimerStore_RebuildFromDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Timer))
	})
	return _c
}

func (_c *MockTimerStore_RebuildFromDB_Call) Return(_a0 error) *MockTimerStore_RebuildFromDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimerStore_RebuildFromDB_Call) RunAndReturn(run func(context.Context, []domain.Timer) error) *MockTimerStore_RebuildFromDB_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleTimer provides a mock function with given fields: ctx, timerID, fireTimeMs
func (_m *MockTimerStore) ScheduleTimer(ctx context.Context, timerID string, fireTimeMs int64) error {
	ret := _m.Called(ctx, timerID, fireTimeMs)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleTimer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, timerID, fireTimeMs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTimerStore_ScheduleTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleTimer'
type MockTimerStore_ScheduleTimer_Call struct {
	*mock.Call
}

// ScheduleTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - timerID string
//   - fireTimeMs int64
func (_e *MockTimerStore_Expecter) ScheduleTimer(ctx interface{}, timerID interface{}, fireTimeMs interface{}) *MockTimerStore_ScheduleTimer_Call {
	return &MockTimerStore_ScheduleTimer_Call{Call: _e.mock.On("ScheduleTimer", ctx, timerID, fireTimeMs)}
}

func (_c *MockTimerStore_ScheduleTimer_Call) Run(run func(ctx context.Context, timerID string, fireTimeMs int64)) *MockTimerStore_ScheduleTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockTimerStore_ScheduleTimer_Call) Return(_a0 error) *MockTimerStore_ScheduleTimer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTimerStore_ScheduleTimer_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockTimerStore_ScheduleTimer_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx
func (_m *MockTimerStore) Subscribe(ctx context.Context) (<-chan struct{}, func()) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan struct{}
	var r1 func()
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan struct{}, func())); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan struct{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) func()); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	return r0, r1
}

// MockTimerStore_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockTimerStore_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTimerStore_Expecter) Subscribe(ctx interface{}) *MockTimerStore_Subscribe_Call {
	return &MockTimerStore_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx)}
}

func (_c *MockTimerStore_Subscribe_Call) Run(run func(ctx context.Context)) *MockTimerStore_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTimerStore_Subscribe_Call) Return(_a0 <-chan struct{}, _a1 func()) *MockTimerStore_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTimerStore_Subscribe_Call) RunAndReturn(run func(context.Context) (<-chan struct{}, func())) *MockTimerStore_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTimerStore creates a new instance of MockTimerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTimerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTimerStore {
	mock := &MockTimerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
