// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "mini-workflow/history/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockExecutionRepository is an autogenerated mock type for the ExecutionRepository type
type MockExecutionRepository struct {
	mock.Mock
}

type MockExecutionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutionRepository) EXPECT() *MockExecutionRepository_Expecter {
	return &MockExecutionRepository_Expecter{mock: &_m.Mock}
}

// CreateWorkflowExecution provides a mock function with given fields: ctx, exec, initialEvent
func (_m *MockExecutionRepository) CreateWorkflowExecution(ctx context.Context, exec *domain.WorkflowExecution, initialEvent *domain.HistoryEvent) error {
	ret := _m.Called(ctx, exec, initialEvent)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkflowExecution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkflowExecution, *domain.HistoryEvent) error); ok {
		r0 = rf(ctx, exec, initialEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_CreateWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkflowExecution'
type MockExecutionRepository_CreateWorkflowExecution_Call struct {
	*mock.Call
}

// CreateWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - exec *domain.WorkflowExecution
//   - initialEvent *domain.HistoryEvent
func (_e *MockExecutionRepository_Expecter) CreateWorkflowExecution(ctx interface{}, exec interface{}, initialEvent interface{}) *MockExecutionRepository_CreateWorkflowExecution_Call {
	return &MockExecutionRepository_CreateWorkflowExecution_Call{Call: _e.mock.On("CreateWorkflowExecution", ctx, exec, initialEvent)}
}

func (_c *MockExecutionRepository_CreateWorkflowExecution_Call) Run(run func(ctx context.Context, exec *domain.WorkflowExecution, initialEvent *domain.HistoryEvent)) *MockExecutionRepository_CreateWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.WorkflowExecution), args[2].(*domain.HistoryEvent))
	})
	return _c
}

func (_c *MockExecutionRepository_CreateWorkflowExecution_Call) Return(_a0 error) *MockExecutionRepository_CreateWorkflowExecution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_CreateWorkflowExecution_Call) RunAndReturn(run func(context.Context, *domain.WorkflowExecution, *domain.HistoryEvent) error) *MockExecutionRepository_CreateWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// FindRunningWorkflow provides a mock function with given fields: ctx, namespace, workflowID
func (_m *MockExecutionRepository) FindRunningWorkflow(ctx context.Context, namespace string, workflowID string) (*domain.WorkflowExecution, error) {
	ret := _m.Called(ctx, namespace, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for FindRunningWorkflow")
	}

	var r0 *domain.WorkflowExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.WorkflowExecution, error)); ok {
		return rf(ctx, namespace, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.WorkflowExecution); ok {
		r0 = rf(ctx, namespace, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_FindRunningWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRunningWorkflow'
type MockExecutionRepository_FindRunningWorkflow_Call struct {
	*mock.Call
}

// FindRunningWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - workflowID string
func (_e *MockExecutionRepository_Expecter) FindRunningWorkflow(ctx interface{}, namespace interface{}, workflowID interface{}) *MockExecutionRepository_FindRunningWorkflow_Call {
	return &MockExecutionRepository_FindRunningWorkflow_Call{Call: _e.mock.On("FindRunningWorkflow", ctx, namespace, workflowID)}
}

func (_c *MockExecutionRepository_FindRunningWorkflow_Call) Run(run func(ctx context.Context, namespace string, workflowID string)) *MockExecutionRepository_FindRunningWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockExecutionRepository_FindRunningWorkflow_Call) Return(_a0 *domain.WorkflowExecution, _a1 error) *MockExecutionRepository_FindRunningWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_FindRunningWorkflow_Call) RunAndReturn(run func(context.Context, string, string) (*domain.WorkflowExecution, error)) *MockExecutionRepository_FindRunningWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityState provides a mock function with given fields: ctx, namespace, workflowID, runID, activityID
func (_m *MockExecutionRepository) GetActivityState(ctx context.Context, namespace string, workflowID string, runID uuid.UUID, activityID string) (*domain.ActivityState, error) {
	ret := _m.Called(ctx, namespace, workflowID, runID, activityID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityState")
	}

	var r0 *domain.ActivityState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, string) (*domain.ActivityState, error)); ok {
		return rf(ctx, namespace, workflowID, runID, activityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, string) *domain.ActivityState); ok {
		r0 = rf(ctx, namespace, workflowID, runID, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ActivityState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID, string) error); ok {
		r1 = rf(ctx, namespace, workflowID, runID, activityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_GetActivityState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityState'
type MockExecutionRepository_GetActivityState_Call struct {
	*mock.Call
}

// GetActivityState is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - workflowID string
//   - runID uuid.UUID
//   - activityID string
func (_e *MockExecutionRepository_Expecter) GetActivityState(ctx interface{}, namespace interface{}, workflowID interface{}, runID interface{}, activityID interface{}) *MockExecutionRepository_GetActivityState_Call {
	return &MockExecutionRepository_GetActivityState_Call{Call: _e.mock.On("GetActivityState", ctx, namespace, workflowID, runID, activityID)}
}

func (_c *MockExecutionRepository_GetActivityState_Call) Run(run func(ctx context.Context, namespace string, workflowID string, runID uuid.UUID, activityID string)) *MockExecutionRepository_GetActivityState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MockExecutionRepository_GetActivityState_Call) Return(_a0 *domain.ActivityState, _a1 error) *MockExecutionRepository_GetActivityState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_GetActivityState_Call) RunAndReturn(run func(context.Context, string, string, uuid.UUID, string) (*domain.ActivityState, error)) *MockExecutionRepository_GetActivityState_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityTimeoutTimer provides a mock function with given fields: ctx, namespace, workflowID, runID, activityID
func (_m *MockExecutionRepository) GetActivityTimeoutTimer(ctx context.Context, namespace string, workflowID string, runID uuid.UUID, activityID string) (*domain.Timer, error) {
	ret := _m.Called(ctx, namespace, workflowID, runID, activityID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityTimeoutTimer")
	}

	var r0 *domain.Timer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, string) (*domain.Timer, error)); ok {
		return rf(ctx, namespace, workflowID, runID, activityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, string) *domain.Timer); ok {
		r0 = rf(ctx, namespace, workflowID, runID, activityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Timer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID, string) error); ok {
		r1 = rf(ctx, namespace, workflowID, runID, activityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_GetActivityTimeoutTimer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityTimeoutTimer'
type MockExecutionRepository_GetActivityTimeoutTimer_Call struct {
	*mock.Call
}

// GetActivityTimeoutTimer is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - workflowID string
//   - runID uuid.UUID
//   - activityID string
func (_e *MockExecutionRepository_Expecter) GetActivityTimeoutTimer(ctx interface{}, namespace interface{}, workflowID interface{}, runID interface{}, activityID interface{}) *MockExecutionRepository_GetActivityTimeoutTimer_Call {
	return &MockExecutionRepository_GetActivityTimeoutTimer_Call{Call: _e.mock.On("GetActivityTimeoutTimer", ctx, namespace, workflowID, runID, activityID)}
}

func (_c *MockExecutionRepository_GetActivityTimeoutTimer_Call) Run(run func(ctx context.Context, namespace string, workflowID string, runID uuid.UUID, activityID string)) *MockExecutionRepository_GetActivityTimeoutTimer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MockExecutionRepository_GetActivityTimeoutTimer_Call) Return(_a0 *domain.Timer, _a1 error) *MockExecutionRepository_GetActivityTimeoutTimer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_GetActivityTimeoutTimer_Call) RunAndReturn(run func(context.Context, string, string, uuid.UUID, string) (*domain.Timer, error)) *MockExecutionRepository_GetActivityTimeoutTimer_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoryEvents provides a mock function with given fields: ctx, namespace, workflowID, runID
func (_m *MockExecutionRepository) GetHistoryEvents(ctx context.Context, namespace string, workflowID string, runID uuid.UUID) ([]domain.HistoryEvent, error) {
	ret := _m.Called(ctx, namespace, workflowID, runID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryEvents")
	}

	var r0 []domain.HistoryEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) ([]domain.HistoryEvent, error)); ok {
		return rf(ctx, namespace, workflowID, runID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) []domain.HistoryEvent); ok {
		r0 = rf(ctx, namespace, workflowID, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.HistoryEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID) error); ok {
		r1 = rf(ctx, namespace, workflowID, runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_GetHistoryEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryEvents'
type MockExecutionRepository_GetHistoryEvents_Call struct {
	*mock.Call
}

// GetHistoryEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - workflowID string
//   - runID uuid.UUID
func (_e *MockExecutionRepository_Expecter) GetHistoryEvents(ctx interface{}, namespace interface{}, workflowID interface{}, runID interface{}) *MockExecutionRepository_GetHistoryEvents_Call {
	return &MockExecutionRepository_GetHistoryEvents_Call{Call: _e.mock.On("GetHistoryEvents", ctx, namespace, workflowID, runID)}
}

func (_c *MockExecutionRepository_GetHistoryEvents_Call) Run(run func(ctx context.Context, namespace string, workflowID string, runID uuid.UUID)) *MockExecutionRepository_GetHistoryEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockExecutionRepository_GetHistoryEvents_Call) Return(_a0 []domain.HistoryEvent, _a1 error) *MockExecutionRepository_GetHistoryEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_GetHistoryEvents_Call) RunAndReturn(run func(context.Context, string, string, uuid.UUID) ([]domain.HistoryEvent, error)) *MockExecutionRepository_GetHistoryEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetNonFiredTimers provides a mock function with given fields: ctx, upTo
func (_m *MockExecutionRepository) GetNonFiredTimers(ctx context.Context, upTo time.Time) ([]domain.Timer, error) {
	ret := _m.Called(ctx, upTo)

	if len(ret) == 0 {
		panic("no return value specified for GetNonFiredTimers")
	}

	var r0 []domain.Timer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.Timer, error)); ok {
		return rf(ctx, upTo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []domain.Timer); ok {
		r0 = rf(ctx, upTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Timer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, upTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_GetNonFiredTimers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNonFiredTimers'
type MockExecutionRepository_GetNonFiredTimers_Call struct {
	*mock.Call
}

// GetNonFiredTimers is a helper method to define mock.On call
//   - ctx context.Context
//   - upTo time.Time
func (_e *MockExecutionRepository_Expecter) GetNonFiredTimers(ctx interface{}, upTo interface{}) *MockExecutionRepository_GetNonFiredTimers_Call {
	return &MockExecutionRepository_GetNonFiredTimers_Call{Call: _e.mock.On("GetNonFiredTimers", ctx, upTo)}
}

func (_c *MockExecutionRepository_GetNonFiredTimers_Call) Run(run func(ctx context.Context, upTo time.Time)) *MockExecutionRepository_GetNonFiredTimers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockExecutionRepository_GetNonFiredTimers_Call) Return(_a0 []domain.Timer, _a1 error) *MockExecutionRepository_GetNonFiredTimers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_GetNonFiredTimers_Call) RunAndReturn(run func(context.Context, time.Time) ([]domain.Timer, error)) *MockExecutionRepository_GetNonFiredTimers_Call {
	_c.Call.Return(run)
	return _c
}

// GetTimerByID provides a mock function with given fields: ctx, timerID
func (_m *MockExecutionRepository) GetTimerByID(ctx context.Context, timerID uuid.UUID) (*domain.Timer, error) {
	ret := _m.Called(ctx, timerID)

	if len(ret) == 0 {
		panic("no return value specified for GetTimerByID")
	}

	var r0 *domain.Timer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Timer, error)); ok {
		return rf(ctx, timerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Timer); ok {
		r0 = rf(ctx, timerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Timer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, timerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_GetTimerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTimerByID'
type MockExecutionRepository_GetTimerByID_Call struct {
	*mock.Call
}

// GetTimerByID is a helper method to define mock.On call
//   - ctx context.Context
//   - timerID uuid.UUID
func (_e *MockExecutionRepository_Expecter) GetTimerByID(ctx interface{}, timerID interface{}) *MockExecutionRepository_GetTimerByID_Call {
	return &MockExecutionRepository_GetTimerByID_Call{Call: _e.mock.On("GetTimerByID", ctx, timerID)}
}

func (_c *MockExecutionRepository_GetTimerByID_Call) Run(run func(ctx context.Context, timerID uuid.UUID)) *MockExecutionRepository_GetTimerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExecutionRepository_GetTimerByID_Call) Return(_a0 *domain.Timer, _a1 error) *MockExecutionRepository_GetTimerByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_GetTimerByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Timer, error)) *MockExecutionRepository_GetTimerByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowExecution provides a mock function with given fields: ctx, namespace, workflowID, runID
func (_m *MockExecutionRepository) GetWorkflowExecution(ctx context.Context, namespace string, workflowID string, runID uuid.UUID) (*domain.WorkflowExecution, error) {
	ret := _m.Called(ctx, namespace, workflowID, runID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowExecution")
	}

	var r0 *domain.WorkflowExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) (*domain.WorkflowExecution, error)); ok {
		return rf(ctx, namespace, workflowID, runID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) *domain.WorkflowExecution); ok {
		r0 = rf(ctx, namespace, workflowID, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID) error); ok {
		r1 = rf(ctx, namespace, workflowID, runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExecutionRepository_GetWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowExecution'
type MockExecutionRepository_GetWorkflowExecution_Call struct {
	*mock.Call
}

// GetWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - workflowID string
//   - runID uuid.UUID
func (_e *MockExecutionRepository_Expecter) GetWorkflowExecution(ctx interface{}, namespace interface{}, workflowID interface{}, runID interface{}) *MockExecutionRepository_GetWorkflowExecution_Call {
	return &MockExecutionRepository_GetWorkflowExecution_Call{Call: _e.mock.On("GetWorkflowExecution", ctx, namespace, workflowID, runID)}
}

func (_c *MockExecutionRepository_GetWorkflowExecution_Call) Run(run func(ctx context.Context, namespace string, workflowID string, runID uuid.UUID)) *MockExecutionRepository_GetWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockExecutionRepository_GetWorkflowExecution_Call) Return(_a0 *domain.WorkflowExecution, _a1 error) *MockExecutionRepository_GetWorkflowExecution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExecutionRepository_GetWorkflowExecution_Call) RunAndReturn(run func(context.Context, string, string, uuid.UUID) (*domain.WorkflowExecution, error)) *MockExecutionRepository_GetWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// MarkTimerFired provides a mock function with given fields: ctx, timerID
func (_m *MockExecutionRepository) MarkTimerFired(ctx context.Context, timerID uuid.UUID) error {
	ret := _m.Called(ctx, timerID)

	if len(ret) == 0 {
		panic("no return value specified for MarkTimerFired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, timerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_MarkTimerFired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkTimerFired'
type MockExecutionRepository_MarkTimerFired_Call struct {
	*mock.Call
}

// MarkTimerFired is a helper method to define mock.On call
//   - ctx context.Context
//   - timerID uuid.UUID
func (_e *MockExecutionRepository_Expecter) MarkTimerFired(ctx interface{}, timerID interface{}) *MockExecutionRepository_MarkTimerFired_Call {
	return &MockExecutionRepository_MarkTimerFired_Call{Call: _e.mock.On("MarkTimerFired", ctx, timerID)}
}

func (_c *MockExecutionRepository_MarkTimerFired_Call) Run(run func(ctx context.Context, timerID uuid.UUID)) *MockExecutionRepository_MarkTimerFired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockExecutionRepository_MarkTimerFired_Call) Return(_a0 error) *MockExecutionRepository_MarkTimerFired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_MarkTimerFired_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockExecutionRepository_MarkTimerFired_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTimerFireTime provides a mock function with given fields: ctx, timerID, newFireTime
func (_m *MockExecutionRepository) UpdateTimerFireTime(ctx context.Context, timerID uuid.UUID, newFireTime time.Time) error {
	ret := _m.Called(ctx, timerID, newFireTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTimerFireTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, timerID, newFireTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_UpdateTimerFireTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTimerFireTime'
type MockExecutionRepository_UpdateTimerFireTime_Call struct {
	*mock.Call
}

// UpdateTimerFireTime is a helper method to define mock.On call
//   - ctx context.Context
//   - timerID uuid.UUID
//   - newFireTime time.Time
func (_e *MockExecutionRepository_Expecter) UpdateTimerFireTime(ctx interface{}, timerID interface{}, newFireTime interface{}) *MockExecutionRepository_UpdateTimerFireTime_Call {
	return &MockExecutionRepository_UpdateTimerFireTime_Call{Call: _e.mock.On("UpdateTimerFireTime", ctx, timerID, newFireTime)}
}

func (_c *MockExecutionRepository_UpdateTimerFireTime_Call) Run(run func(ctx context.Context, timerID uuid.UUID, newFireTime time.Time)) *MockExecutionRepository_UpdateTimerFireTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockExecutionRepository_UpdateTimerFireTime_Call) Return(_a0 error) *MockExecutionRepository_UpdateTimerFireTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_UpdateTimerFireTime_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockExecutionRepository_UpdateTimerFireTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkflowExecution provides a mock function with given fields: ctx, exec, expectedVersion, events, activitiesToUpsert, timersToInsert
func (_m *MockExecutionRepository) UpdateWorkflowExecution(ctx context.Context, exec *domain.WorkflowExecution, expectedVersion int64, events []domain.HistoryEvent, activitiesToUpsert []domain.ActivityState, timersToInsert []domain.Timer) error {
	ret := _m.Called(ctx, exec, expectedVersion, events, activitiesToUpsert, timersToInsert)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkflowExecution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkflowExecution, int64, []domain.HistoryEvent, []domain.ActivityState, []domain.Timer) error); ok {
		r0 = rf(ctx, exec, expectedVersion, events, activitiesToUpsert, timersToInsert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExecutionRepository_UpdateWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkflowExecution'
type MockExecutionRepository_UpdateWorkflowExecution_Call struct {
	*mock.Call
}

// UpdateWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - exec *domain.WorkflowExecution
//   - expectedVersion int64
//   - events []domain.HistoryEvent
//   - activitiesToUpsert []domain.ActivityState
//   - timersToInsert []domain.Timer
func (_e *MockExecutionRepository_Expecter) UpdateWorkflowExecution(ctx interface{}, exec interface{}, expectedVersion interface{}, events interface{}, activitiesToUpsert interface{}, timersToInsert interface{}) *MockExecutionRepository_UpdateWorkflowExecution_Call {
	return &MockExecutionRepository_UpdateWorkflowExecution_Call{Call: _e.mock.On("UpdateWorkflowExecution", ctx, exec, expectedVersion, events, activitiesToUpsert, timersToInsert)}
}

func (_c *MockExecutionRepository_UpdateWorkflowExecution_Call) Run(run func(ctx context.Context, exec *domain.WorkflowExecution, expectedVersion int64, events []domain.HistoryEvent, activitiesToUpsert []domain.ActivityState, timersToInsert []domain.Timer)) *MockExecutionRepository_UpdateWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.WorkflowExecution), args[2].(int64), args[3].([]domain.HistoryEvent), args[4].([]domain.ActivityState), args[5].([]domain.Timer))
	})
	return _c
}

func (_c *MockExecutionRepository_UpdateWorkflowExecution_Call) Return(_a0 error) *MockExecutionRepository_UpdateWorkflowExecution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExecutionRepository_UpdateWorkflowExecution_Call) RunAndReturn(run func(context.Context, *domain.WorkflowExecution, int64, []domain.HistoryEvent, []domain.ActivityState, []domain.Timer) error) *MockExecutionRepository_UpdateWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExecutionRepository creates a new instance of MockExecutionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutionRepository {
	mock := &MockExecutionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
