// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	workflow "mini-workflow/api"
)

// MockHistoryService is an autogenerated mock type for the HistoryService type
type MockHistoryService struct {
	mock.Mock
}

type MockHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryService) EXPECT() *MockHistoryService_Expecter {
	return &MockHistoryService_Expecter{mock: &_m.Mock}
}

// GetWorkflowExecutionHistory provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) GetWorkflowExecutionHistory(ctx context.Context, req *workflow.GetHistoryRequest) (*workflow.GetHistoryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowExecutionHistory")
	}

	var r0 *workflow.GetHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.GetHistoryRequest) (*workflow.GetHistoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.GetHistoryRequest) *workflow.GetHistoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.GetHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.GetHistoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_GetWorkflowExecutionHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowExecutionHistory'
type MockHistoryService_GetWorkflowExecutionHistory_Call struct {
	*mock.Call
}

// GetWorkflowExecutionHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.GetHistoryRequest
func (_e *MockHistoryService_Expecter) GetWorkflowExecutionHistory(ctx interface{}, req interface{}) *MockHistoryService_GetWorkflowExecutionHistory_Call {
	return &MockHistoryService_GetWorkflowExecutionHistory_Call{Call: _e.mock.On("GetWorkflowExecutionHistory", ctx, req)}
}

func (_c *MockHistoryService_GetWorkflowExecutionHistory_Call) Run(run func(ctx context.Context, req *workflow.GetHistoryRequest)) *MockHistoryService_GetWorkflowExecutionHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.GetHistoryRequest))
	})
	return _c
}

func (_c *MockHistoryService_GetWorkflowExecutionHistory_Call) Return(_a0 *workflow.GetHistoryResponse, _a1 error) *MockHistoryService_GetWorkflowExecutionHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_GetWorkflowExecutionHistory_Call) RunAndReturn(run func(context.Context, *workflow.GetHistoryRequest) (*workflow.GetHistoryResponse, error)) *MockHistoryService_GetWorkflowExecutionHistory_Call {
	_c.Call.Return(run)
	return _c
}

// QueryWorkflowExecution provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) QueryWorkflowExecution(ctx context.Context, req *workflow.QueryWorkflowRequest) (*workflow.QueryWorkflowResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryWorkflowExecution")
	}

	var r0 *workflow.QueryWorkflowResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.QueryWorkflowRequest) (*workflow.QueryWorkflowResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.QueryWorkflowRequest) *workflow.QueryWorkflowResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.QueryWorkflowResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.QueryWorkflowRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_QueryWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWorkflowExecution'
type MockHistoryService_QueryWorkflowExecution_Call struct {
	*mock.Call
}

// QueryWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.QueryWorkflowRequest
func (_e *MockHistoryService_Expecter) QueryWorkflowExecution(ctx interface{}, req interface{}) *MockHistoryService_QueryWorkflowExecution_Call {
	return &MockHistoryService_QueryWorkflowExecution_Call{Call: _e.mock.On("QueryWorkflowExecution", ctx, req)}
}

func (_c *MockHistoryService_QueryWorkflowExecution_Call) Run(run func(ctx context.Context, req *workflow.QueryWorkflowRequest)) *MockHistoryService_QueryWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.QueryWorkflowRequest))
	})
	return _c
}

func (_c *MockHistoryService_QueryWorkflowExecution_Call) Return(_a0 *workflow.QueryWorkflowResponse, _a1 error) *MockHistoryService_QueryWorkflowExecution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_QueryWorkflowExecution_Call) RunAndReturn(run func(context.Context, *workflow.QueryWorkflowRequest) (*workflow.QueryWorkflowResponse, error)) *MockHistoryService_QueryWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// RecordActivityTaskCompleted provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordActivityTaskCompleted(ctx context.Context, req *workflow.RecordActivityTaskCompletedRequest) (*workflow.RecordActivityTaskCompletedResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordActivityTaskCompleted")
	}

	var r0 *workflow.RecordActivityTaskCompletedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskCompletedRequest) (*workflow.RecordActivityTaskCompletedResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskCompletedRequest) *workflow.RecordActivityTaskCompletedResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordActivityTaskCompletedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordActivityTaskCompletedRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordActivityTaskCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordActivityTaskCompleted'
type MockHistoryService_RecordActivityTaskCompleted_Call struct {
	*mock.Call
}

// RecordActivityTaskCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordActivityTaskCompletedRequest
func (_e *MockHistoryService_Expecter) RecordActivityTaskCompleted(ctx interface{}, req interface{}) *MockHistoryService_RecordActivityTaskCompleted_Call {
	return &MockHistoryService_RecordActivityTaskCompleted_Call{Call: _e.mock.On("RecordActivityTaskCompleted", ctx, req)}
}

func (_c *MockHistoryService_RecordActivityTaskCompleted_Call) Run(run func(ctx context.Context, req *workflow.RecordActivityTaskCompletedRequest)) *MockHistoryService_RecordActivityTaskCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordActivityTaskCompletedRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskCompleted_Call) Return(_a0 *workflow.RecordActivityTaskCompletedResponse, _a1 error) *MockHistoryService_RecordActivityTaskCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskCompleted_Call) RunAndReturn(run func(context.Context, *workflow.RecordActivityTaskCompletedRequest) (*workflow.RecordActivityTaskCompletedResponse, error)) *MockHistoryService_RecordActivityTaskCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// RecordActivityTaskFailed provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordActivityTaskFailed(ctx context.Context, req *workflow.RecordActivityTaskFailedRequest) (*workflow.RecordActivityTaskFailedResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordActivityTaskFailed")
	}

	var r0 *workflow.RecordActivityTaskFailedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskFailedRequest) (*workflow.RecordActivityTaskFailedResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskFailedRequest) *workflow.RecordActivityTaskFailedResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordActivityTaskFailedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordActivityTaskFailedRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordActivityTaskFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordActivityTaskFailed'
type MockHistoryService_RecordActivityTaskFailed_Call struct {
	*mock.Call
}

// RecordActivityTaskFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordActivityTaskFailedRequest
func (_e *MockHistoryService_Expecter) RecordActivityTaskFailed(ctx interface{}, req interface{}) *MockHistoryService_RecordActivityTaskFailed_Call {
	return &MockHistoryService_RecordActivityTaskFailed_Call{Call: _e.mock.On("RecordActivityTaskFailed", ctx, req)}
}

func (_c *MockHistoryService_RecordActivityTaskFailed_Call) Run(run func(ctx context.Context, req *workflow.RecordActivityTaskFailedRequest)) *MockHistoryService_RecordActivityTaskFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordActivityTaskFailedRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskFailed_Call) Return(_a0 *workflow.RecordActivityTaskFailedResponse, _a1 error) *MockHistoryService_RecordActivityTaskFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskFailed_Call) RunAndReturn(run func(context.Context, *workflow.RecordActivityTaskFailedRequest) (*workflow.RecordActivityTaskFailedResponse, error)) *MockHistoryService_RecordActivityTaskFailed_Call {
	_c.Call.Return(run)
	return _c
}

// RecordActivityTaskHeartbeat provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordActivityTaskHeartbeat(ctx context.Context, req *workflow.RecordActivityTaskHeartbeatRequest) (*workflow.RecordActivityTaskHeartbeatResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordActivityTaskHeartbeat")
	}

	var r0 *workflow.RecordActivityTaskHeartbeatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskHeartbeatRequest) (*workflow.RecordActivityTaskHeartbeatResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskHeartbeatRequest) *workflow.RecordActivityTaskHeartbeatResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordActivityTaskHeartbeatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordActivityTaskHeartbeatRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordActivityTaskHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordActivityTaskHeartbeat'
type MockHistoryService_RecordActivityTaskHeartbeat_Call struct {
	*mock.Call
}

// RecordActivityTaskHeartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordActivityTaskHeartbeatRequest
func (_e *MockHistoryService_Expecter) RecordActivityTaskHeartbeat(ctx interface{}, req interface{}) *MockHistoryService_RecordActivityTaskHeartbeat_Call {
	return &MockHistoryService_RecordActivityTaskHeartbeat_Call{Call: _e.mock.On("RecordActivityTaskHeartbeat", ctx, req)}
}

func (_c *MockHistoryService_RecordActivityTaskHeartbeat_Call) Run(run func(ctx context.Context, req *workflow.RecordActivityTaskHeartbeatRequest)) *MockHistoryService_RecordActivityTaskHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordActivityTaskHeartbeatRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskHeartbeat_Call) Return(_a0 *workflow.RecordActivityTaskHeartbeatResponse, _a1 error) *MockHistoryService_RecordActivityTaskHeartbeat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskHeartbeat_Call) RunAndReturn(run func(context.Context, *workflow.RecordActivityTaskHeartbeatRequest) (*workflow.RecordActivityTaskHeartbeatResponse, error)) *MockHistoryService_RecordActivityTaskHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// RecordActivityTaskStarted provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordActivityTaskStarted(ctx context.Context, req *workflow.RecordActivityTaskStartedRequest) (*workflow.RecordActivityTaskStartedResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordActivityTaskStarted")
	}

	var r0 *workflow.RecordActivityTaskStartedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskStartedRequest) (*workflow.RecordActivityTaskStartedResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordActivityTaskStartedRequest) *workflow.RecordActivityTaskStartedResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordActivityTaskStartedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordActivityTaskStartedRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordActivityTaskStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordActivityTaskStarted'
type MockHistoryService_RecordActivityTaskStarted_Call struct {
	*mock.Call
}

// RecordActivityTaskStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordActivityTaskStartedRequest
func (_e *MockHistoryService_Expecter) RecordActivityTaskStarted(ctx interface{}, req interface{}) *MockHistoryService_RecordActivityTaskStarted_Call {
	return &MockHistoryService_RecordActivityTaskStarted_Call{Call: _e.mock.On("RecordActivityTaskStarted", ctx, req)}
}

func (_c *MockHistoryService_RecordActivityTaskStarted_Call) Run(run func(ctx context.Context, req *workflow.RecordActivityTaskStartedRequest)) *MockHistoryService_RecordActivityTaskStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordActivityTaskStartedRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskStarted_Call) Return(_a0 *workflow.RecordActivityTaskStartedResponse, _a1 error) *MockHistoryService_RecordActivityTaskStarted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordActivityTaskStarted_Call) RunAndReturn(run func(context.Context, *workflow.RecordActivityTaskStartedRequest) (*workflow.RecordActivityTaskStartedResponse, error)) *MockHistoryService_RecordActivityTaskStarted_Call {
	_c.Call.Return(run)
	return _c
}

// RecordWorkflowExecutionStarted provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordWorkflowExecutionStarted(ctx context.Context, req *workflow.RecordWorkflowExecutionStartedRequest) (*workflow.RecordWorkflowExecutionStartedResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordWorkflowExecutionStarted")
	}

	var r0 *workflow.RecordWorkflowExecutionStartedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowExecutionStartedRequest) (*workflow.RecordWorkflowExecutionStartedResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowExecutionStartedRequest) *workflow.RecordWorkflowExecutionStartedResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordWorkflowExecutionStartedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordWorkflowExecutionStartedRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordWorkflowExecutionStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordWorkflowExecutionStarted'
type MockHistoryService_RecordWorkflowExecutionStarted_Call struct {
	*mock.Call
}

// RecordWorkflowExecutionStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordWorkflowExecutionStartedRequest
func (_e *MockHistoryService_Expecter) RecordWorkflowExecutionStarted(ctx interface{}, req interface{}) *MockHistoryService_RecordWorkflowExecutionStarted_Call {
	return &MockHistoryService_RecordWorkflowExecutionStarted_Call{Call: _e.mock.On("RecordWorkflowExecutionStarted", ctx, req)}
}

func (_c *MockHistoryService_RecordWorkflowExecutionStarted_Call) Run(run func(ctx context.Context, req *workflow.RecordWorkflowExecutionStartedRequest)) *MockHistoryService_RecordWorkflowExecutionStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordWorkflowExecutionStartedRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordWorkflowExecutionStarted_Call) Return(_a0 *workflow.RecordWorkflowExecutionStartedResponse, _a1 error) *MockHistoryService_RecordWorkflowExecutionStarted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordWorkflowExecutionStarted_Call) RunAndReturn(run func(context.Context, *workflow.RecordWorkflowExecutionStartedRequest) (*workflow.RecordWorkflowExecutionStartedResponse, error)) *MockHistoryService_RecordWorkflowExecutionStarted_Call {
	_c.Call.Return(run)
	return _c
}

// RecordWorkflowTaskCompleted provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordWorkflowTaskCompleted(ctx context.Context, req *workflow.RecordWorkflowTaskCompletedHistoryRequest) (*workflow.RecordWorkflowTaskCompletedHistoryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordWorkflowTaskCompleted")
	}

	var r0 *workflow.RecordWorkflowTaskCompletedHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowTaskCompletedHistoryRequest) (*workflow.RecordWorkflowTaskCompletedHistoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowTaskCompletedHistoryRequest) *workflow.RecordWorkflowTaskCompletedHistoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordWorkflowTaskCompletedHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordWorkflowTaskCompletedHistoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordWorkflowTaskCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordWorkflowTaskCompleted'
type MockHistoryService_RecordWorkflowTaskCompleted_Call struct {
	*mock.Call
}

// RecordWorkflowTaskCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordWorkflowTaskCompletedHistoryRequest
func (_e *MockHistoryService_Expecter) RecordWorkflowTaskCompleted(ctx interface{}, req interface{}) *MockHistoryService_RecordWorkflowTaskCompleted_Call {
	return &MockHistoryService_RecordWorkflowTaskCompleted_Call{Call: _e.mock.On("RecordWorkflowTaskCompleted", ctx, req)}
}

func (_c *MockHistoryService_RecordWorkflowTaskCompleted_Call) Run(run func(ctx context.Context, req *workflow.RecordWorkflowTaskCompletedHistoryRequest)) *MockHistoryService_RecordWorkflowTaskCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordWorkflowTaskCompletedHistoryRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordWorkflowTaskCompleted_Call) Return(_a0 *workflow.RecordWorkflowTaskCompletedHistoryResponse, _a1 error) *MockHistoryService_RecordWorkflowTaskCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordWorkflowTaskCompleted_Call) RunAndReturn(run func(context.Context, *workflow.RecordWorkflowTaskCompletedHistoryRequest) (*workflow.RecordWorkflowTaskCompletedHistoryResponse, error)) *MockHistoryService_RecordWorkflowTaskCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// RecordWorkflowTaskFailed provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordWorkflowTaskFailed(ctx context.Context, req *workflow.RecordWorkflowTaskFailedHistoryRequest) (*workflow.RecordWorkflowTaskFailedHistoryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordWorkflowTaskFailed")
	}

	var r0 *workflow.RecordWorkflowTaskFailedHistoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowTaskFailedHistoryRequest) (*workflow.RecordWorkflowTaskFailedHistoryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowTaskFailedHistoryRequest) *workflow.RecordWorkflowTaskFailedHistoryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordWorkflowTaskFailedHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordWorkflowTaskFailedHistoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordWorkflowTaskFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordWorkflowTaskFailed'
type MockHistoryService_RecordWorkflowTaskFailed_Call struct {
	*mock.Call
}

// RecordWorkflowTaskFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordWorkflowTaskFailedHistoryRequest
func (_e *MockHistoryService_Expecter) RecordWorkflowTaskFailed(ctx interface{}, req interface{}) *MockHistoryService_RecordWorkflowTaskFailed_Call {
	return &MockHistoryService_RecordWorkflowTaskFailed_Call{Call: _e.mock.On("RecordWorkflowTaskFailed", ctx, req)}
}

func (_c *MockHistoryService_RecordWorkflowTaskFailed_Call) Run(run func(ctx context.Context, req *workflow.RecordWorkflowTaskFailedHistoryRequest)) *MockHistoryService_RecordWorkflowTaskFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordWorkflowTaskFailedHistoryRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordWorkflowTaskFailed_Call) Return(_a0 *workflow.RecordWorkflowTaskFailedHistoryResponse, _a1 error) *MockHistoryService_RecordWorkflowTaskFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordWorkflowTaskFailed_Call) RunAndReturn(run func(context.Context, *workflow.RecordWorkflowTaskFailedHistoryRequest) (*workflow.RecordWorkflowTaskFailedHistoryResponse, error)) *MockHistoryService_RecordWorkflowTaskFailed_Call {
	_c.Call.Return(run)
	return _c
}

// RecordWorkflowTaskStarted provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) RecordWorkflowTaskStarted(ctx context.Context, req *workflow.RecordWorkflowTaskStartedRequest) (*workflow.RecordWorkflowTaskStartedResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RecordWorkflowTaskStarted")
	}

	var r0 *workflow.RecordWorkflowTaskStartedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowTaskStartedRequest) (*workflow.RecordWorkflowTaskStartedResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.RecordWorkflowTaskStartedRequest) *workflow.RecordWorkflowTaskStartedResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.RecordWorkflowTaskStartedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.RecordWorkflowTaskStartedRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_RecordWorkflowTaskStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordWorkflowTaskStarted'
type MockHistoryService_RecordWorkflowTaskStarted_Call struct {
	*mock.Call
}

// RecordWorkflowTaskStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.RecordWorkflowTaskStartedRequest
func (_e *MockHistoryService_Expecter) RecordWorkflowTaskStarted(ctx interface{}, req interface{}) *MockHistoryService_RecordWorkflowTaskStarted_Call {
	return &MockHistoryService_RecordWorkflowTaskStarted_Call{Call: _e.mock.On("RecordWorkflowTaskStarted", ctx, req)}
}

func (_c *MockHistoryService_RecordWorkflowTaskStarted_Call) Run(run func(ctx context.Context, req *workflow.RecordWorkflowTaskStartedRequest)) *MockHistoryService_RecordWorkflowTaskStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.RecordWorkflowTaskStartedRequest))
	})
	return _c
}

func (_c *MockHistoryService_RecordWorkflowTaskStarted_Call) Return(_a0 *workflow.RecordWorkflowTaskStartedResponse, _a1 error) *MockHistoryService_RecordWorkflowTaskStarted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_RecordWorkflowTaskStarted_Call) RunAndReturn(run func(context.Context, *workflow.RecordWorkflowTaskStartedRequest) (*workflow.RecordWorkflowTaskStartedResponse, error)) *MockHistoryService_RecordWorkflowTaskStarted_Call {
	_c.Call.Return(run)
	return _c
}

// SignalWorkflowExecution provides a mock function with given fields: ctx, req
func (_m *MockHistoryService) SignalWorkflowExecution(ctx context.Context, req *workflow.SignalWorkflowRequest) (*workflow.SignalWorkflowResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignalWorkflowExecution")
	}

	var r0 *workflow.SignalWorkflowResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.SignalWorkflowRequest) (*workflow.SignalWorkflowResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.SignalWorkflowRequest) *workflow.SignalWorkflowResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.SignalWorkflowResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.SignalWorkflowRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryService_SignalWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignalWorkflowExecution'
type MockHistoryService_SignalWorkflowExecution_Call struct {
	*mock.Call
}

// SignalWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.SignalWorkflowRequest
func (_e *MockHistoryService_Expecter) SignalWorkflowExecution(ctx interface{}, req interface{}) *MockHistoryService_SignalWorkflowExecution_Call {
	return &MockHistoryService_SignalWorkflowExecution_Call{Call: _e.mock.On("SignalWorkflowExecution", ctx, req)}
}

func (_c *MockHistoryService_SignalWorkflowExecution_Call) Run(run func(ctx context.Context, req *workflow.SignalWorkflowRequest)) *MockHistoryService_SignalWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.SignalWorkflowRequest))
	})
	return _c
}

func (_c *MockHistoryService_SignalWorkflowExecution_Call) Return(_a0 *workflow.SignalWorkflowResponse, _a1 error) *MockHistoryService_SignalWorkflowExecution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryService_SignalWorkflowExecution_Call) RunAndReturn(run func(context.Context, *workflow.SignalWorkflowRequest) (*workflow.SignalWorkflowResponse, error)) *MockHistoryService_SignalWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHistoryService creates a new instance of MockHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryService {
	mock := &MockHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
