// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	workflow "mini-workflow/api"
)

// MockMatchingClient is an autogenerated mock type for the MatchingClient type
type MockMatchingClient struct {
	mock.Mock
}

type MockMatchingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchingClient) EXPECT() *MockMatchingClient_Expecter {
	return &MockMatchingClient_Expecter{mock: &_m.Mock}
}

// AddActivityTask provides a mock function with given fields: ctx, req
func (_m *MockMatchingClient) AddActivityTask(ctx context.Context, req *workflow.AddActivityTaskRequest) (*workflow.AddActivityTaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddActivityTask")
	}

	var r0 *workflow.AddActivityTaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddActivityTaskRequest) (*workflow.AddActivityTaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddActivityTaskRequest) *workflow.AddActivityTaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.AddActivityTaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.AddActivityTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingClient_AddActivityTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddActivityTask'
type MockMatchingClient_AddActivityTask_Call struct {
	*mock.Call
}

// AddActivityTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.AddActivityTaskRequest
func (_e *MockMatchingClient_Expecter) AddActivityTask(ctx interface{}, req interface{}) *MockMatchingClient_AddActivityTask_Call {
	return &MockMatchingClient_AddActivityTask_Call{Call: _e.mock.On("AddActivityTask", ctx, req)}
}

func (_c *MockMatchingClient_AddActivityTask_Call) Run(run func(ctx context.Context, req *workflow.AddActivityTaskRequest)) *MockMatchingClient_AddActivityTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.AddActivityTaskRequest))
	})
	return _c
}

func (_c *MockMatchingClient_AddActivityTask_Call) Return(_a0 *workflow.AddActivityTaskResponse, _a1 error) *MockMatchingClient_AddActivityTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingClient_AddActivityTask_Call) RunAndReturn(run func(context.Context, *workflow.AddActivityTaskRequest) (*workflow.AddActivityTaskResponse, error)) *MockMatchingClient_AddActivityTask_Call {
	_c.Call.Return(run)
	return _c
}

// AddWorkflowTask provides a mock function with given fields: ctx, req
func (_m *MockMatchingClient) AddWorkflowTask(ctx context.Context, req *workflow.AddWorkflowTaskRequest) (*workflow.AddWorkflowTaskResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkflowTask")
	}

	var r0 *workflow.AddWorkflowTaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddWorkflowTaskRequest) (*workflow.AddWorkflowTaskResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *workflow.AddWorkflowTaskRequest) *workflow.AddWorkflowTaskResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.AddWorkflowTaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *workflow.AddWorkflowTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMatchingClient_AddWorkflowTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkflowTask'
type MockMatchingClient_AddWorkflowTask_Call struct {
	*mock.Call
}

// AddWorkflowTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req *workflow.AddWorkflowTaskRequest
func (_e *MockMatchingClient_Expecter) AddWorkflowTask(ctx interface{}, req interface{}) *MockMatchingClient_AddWorkflowTask_Call {
	return &MockMatchingClient_AddWorkflowTask_Call{Call: _e.mock.On("AddWorkflowTask", ctx, req)}
}

func (_c *MockMatchingClient_AddWorkflowTask_Call) Run(run func(ctx context.Context, req *workflow.AddWorkflowTaskRequest)) *MockMatchingClient_AddWorkflowTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*workflow.AddWorkflowTaskRequest))
	})
	return _c
}

func (_c *MockMatchingClient_AddWorkflowTask_Call) Return(_a0 *workflow.AddWorkflowTaskResponse, _a1 error) *MockMatchingClient_AddWorkflowTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMatchingClient_AddWorkflowTask_Call) RunAndReturn(run func(context.Context, *workflow.AddWorkflowTaskRequest) (*workflow.AddWorkflowTaskResponse, error)) *MockMatchingClient_AddWorkflowTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMatchingClient creates a new instance of MockMatchingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchingClient {
	mock := &MockMatchingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
