// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workflow Start/Signal/Query
type StartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,3,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Input         []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *StartWorkflowRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *StartWorkflowRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type SignalWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,4,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowRequest) Reset() {
	*x = SignalWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowRequest) ProtoMessage() {}

func (x *SignalWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SignalWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *SignalWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflowRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type SignalWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowResponse) Reset() {
	*x = SignalWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowResponse) ProtoMessage() {}

func (x *SignalWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SignalWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

type QueryWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	QueryType     string                 `protobuf:"bytes,3,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	QueryArgs     []byte                 `protobuf:"bytes,4,opt,name=query_args,json=queryArgs,proto3" json:"query_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWorkflowRequest) Reset() {
	*x = QueryWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkflowRequest) ProtoMessage() {}

func (x *QueryWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkflowRequest.ProtoReflect.Descriptor instead.
func (*QueryWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *QueryWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *QueryWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *QueryWorkflowRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *QueryWorkflowRequest) GetQueryArgs() []byte {
	if x != nil {
		return x.QueryArgs
	}
	return nil
}

type QueryWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryResult   []byte                 `protobuf:"bytes,1,opt,name=query_result,json=queryResult,proto3" json:"query_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWorkflowResponse) Reset() {
	*x = QueryWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWorkflowResponse) ProtoMessage() {}

func (x *QueryWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWorkflowResponse.ProtoReflect.Descriptor instead.
func (*QueryWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *QueryWorkflowResponse) GetQueryResult() []byte {
	if x != nil {
		return x.QueryResult
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetHistoryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*HistoryEvent        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryResponse) GetHistory() []*HistoryEvent {
	if x != nil {
		return x.History
	}
	return nil
}

// Polling Messages
type PollWorkflowTaskQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskQueue     string                 `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollWorkflowTaskQueueRequest) Reset() {
	*x = PollWorkflowTaskQueueRequest{}
	mi := &file_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollWorkflowTaskQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollWorkflowTaskQueueRequest) ProtoMessage() {}

func (x *PollWorkflowTaskQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollWorkflowTaskQueueRequest.ProtoReflect.Descriptor instead.
func (*PollWorkflowTaskQueueRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *PollWorkflowTaskQueueRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *PollWorkflowTaskQueueRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type PollWorkflowTaskQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	History       []*HistoryEvent        `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"` // For Replay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollWorkflowTaskQueueResponse) Reset() {
	*x = PollWorkflowTaskQueueResponse{}
	mi := &file_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollWorkflowTaskQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollWorkflowTaskQueueResponse) ProtoMessage() {}

func (x *PollWorkflowTaskQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollWorkflowTaskQueueResponse.ProtoReflect.Descriptor instead.
func (*PollWorkflowTaskQueueResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *PollWorkflowTaskQueueResponse) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *PollWorkflowTaskQueueResponse) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *PollWorkflowTaskQueueResponse) GetHistory() []*HistoryEvent {
	if x != nil {
		return x.History
	}
	return nil
}

type PollActivityTaskQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskQueue     string                 `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollActivityTaskQueueRequest) Reset() {
	*x = PollActivityTaskQueueRequest{}
	mi := &file_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollActivityTaskQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollActivityTaskQueueRequest) ProtoMessage() {}

func (x *PollActivityTaskQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollActivityTaskQueueRequest.ProtoReflect.Descriptor instead.
func (*PollActivityTaskQueueRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *PollActivityTaskQueueRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *PollActivityTaskQueueRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type PollActivityTaskQueueResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TaskToken               []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	ActivityId              string                 `protobuf:"bytes,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityType            string                 `protobuf:"bytes,3,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	Input                   []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	HeartbeatTimeoutSeconds int32                  `protobuf:"varint,5,opt,name=heartbeat_timeout_seconds,json=heartbeatTimeoutSeconds,proto3" json:"heartbeat_timeout_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PollActivityTaskQueueResponse) Reset() {
	*x = PollActivityTaskQueueResponse{}
	mi := &file_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollActivityTaskQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollActivityTaskQueueResponse) ProtoMessage() {}

func (x *PollActivityTaskQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollActivityTaskQueueResponse.ProtoReflect.Descriptor instead.
func (*PollActivityTaskQueueResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *PollActivityTaskQueueResponse) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *PollActivityTaskQueueResponse) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *PollActivityTaskQueueResponse) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *PollActivityTaskQueueResponse) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PollActivityTaskQueueResponse) GetHeartbeatTimeoutSeconds() int32 {
	if x != nil {
		return x.HeartbeatTimeoutSeconds
	}
	return 0
}

// Respond Messages
type RespondWorkflowTaskCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondWorkflowTaskCompletedRequest) Reset() {
	*x = RespondWorkflowTaskCompletedRequest{}
	mi := &file_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondWorkflowTaskCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondWorkflowTaskCompletedRequest) ProtoMessage() {}

func (x *RespondWorkflowTaskCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondWorkflowTaskCompletedRequest.ProtoReflect.Descriptor instead.
func (*RespondWorkflowTaskCompletedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *RespondWorkflowTaskCompletedRequest) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *RespondWorkflowTaskCompletedRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *RespondWorkflowTaskCompletedRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RespondWorkflowTaskCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondWorkflowTaskCompletedResponse) Reset() {
	*x = RespondWorkflowTaskCompletedResponse{}
	mi := &file_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondWorkflowTaskCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondWorkflowTaskCompletedResponse) ProtoMessage() {}

func (x *RespondWorkflowTaskCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondWorkflowTaskCompletedResponse.ProtoReflect.Descriptor instead.
func (*RespondWorkflowTaskCompletedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{13}
}

type RespondWorkflowTaskFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondWorkflowTaskFailedRequest) Reset() {
	*x = RespondWorkflowTaskFailedRequest{}
	mi := &file_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondWorkflowTaskFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondWorkflowTaskFailedRequest) ProtoMessage() {}

func (x *RespondWorkflowTaskFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondWorkflowTaskFailedRequest.ProtoReflect.Descriptor instead.
func (*RespondWorkflowTaskFailedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *RespondWorkflowTaskFailedRequest) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *RespondWorkflowTaskFailedRequest) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *RespondWorkflowTaskFailedRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RespondWorkflowTaskFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondWorkflowTaskFailedResponse) Reset() {
	*x = RespondWorkflowTaskFailedResponse{}
	mi := &file_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondWorkflowTaskFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondWorkflowTaskFailedResponse) ProtoMessage() {}

func (x *RespondWorkflowTaskFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondWorkflowTaskFailedResponse.ProtoReflect.Descriptor instead.
func (*RespondWorkflowTaskFailedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{15}
}

type RespondActivityTaskCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Identity      string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondActivityTaskCompletedRequest) Reset() {
	*x = RespondActivityTaskCompletedRequest{}
	mi := &file_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondActivityTaskCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondActivityTaskCompletedRequest) ProtoMessage() {}

func (x *RespondActivityTaskCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondActivityTaskCompletedRequest.ProtoReflect.Descriptor instead.
func (*RespondActivityTaskCompletedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *RespondActivityTaskCompletedRequest) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *RespondActivityTaskCompletedRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RespondActivityTaskCompletedRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RespondActivityTaskCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondActivityTaskCompletedResponse) Reset() {
	*x = RespondActivityTaskCompletedResponse{}
	mi := &file_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondActivityTaskCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondActivityTaskCompletedResponse) ProtoMessage() {}

func (x *RespondActivityTaskCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondActivityTaskCompletedResponse.ProtoReflect.Descriptor instead.
func (*RespondActivityTaskCompletedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{17}
}

type RespondActivityTaskFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Identity      string                 `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondActivityTaskFailedRequest) Reset() {
	*x = RespondActivityTaskFailedRequest{}
	mi := &file_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondActivityTaskFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondActivityTaskFailedRequest) ProtoMessage() {}

func (x *RespondActivityTaskFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondActivityTaskFailedRequest.ProtoReflect.Descriptor instead.
func (*RespondActivityTaskFailedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *RespondActivityTaskFailedRequest) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *RespondActivityTaskFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RespondActivityTaskFailedRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *RespondActivityTaskFailedRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type RespondActivityTaskFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondActivityTaskFailedResponse) Reset() {
	*x = RespondActivityTaskFailedResponse{}
	mi := &file_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondActivityTaskFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondActivityTaskFailedResponse) ProtoMessage() {}

func (x *RespondActivityTaskFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondActivityTaskFailedResponse.ProtoReflect.Descriptor instead.
func (*RespondActivityTaskFailedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{19}
}

type RecordActivityTaskHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     []byte                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Details       []byte                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskHeartbeatRequest) Reset() {
	*x = RecordActivityTaskHeartbeatRequest{}
	mi := &file_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskHeartbeatRequest) ProtoMessage() {}

func (x *RecordActivityTaskHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *RecordActivityTaskHeartbeatRequest) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *RecordActivityTaskHeartbeatRequest) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

type RecordActivityTaskHeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CancelRequested bool                   `protobuf:"varint,1,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordActivityTaskHeartbeatResponse) Reset() {
	*x = RecordActivityTaskHeartbeatResponse{}
	mi := &file_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskHeartbeatResponse) ProtoMessage() {}

func (x *RecordActivityTaskHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *RecordActivityTaskHeartbeatResponse) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

// Internal Service Requests (History & Matching)
type RecordWorkflowExecutionStartedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartRequest  *StartWorkflowRequest  `protobuf:"bytes,1,opt,name=start_request,json=startRequest,proto3" json:"start_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowExecutionStartedRequest) Reset() {
	*x = RecordWorkflowExecutionStartedRequest{}
	mi := &file_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowExecutionStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowExecutionStartedRequest) ProtoMessage() {}

func (x *RecordWorkflowExecutionStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowExecutionStartedRequest.ProtoReflect.Descriptor instead.
func (*RecordWorkflowExecutionStartedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *RecordWorkflowExecutionStartedRequest) GetStartRequest() *StartWorkflowRequest {
	if x != nil {
		return x.StartRequest
	}
	return nil
}

type RecordWorkflowExecutionStartedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowExecutionStartedResponse) Reset() {
	*x = RecordWorkflowExecutionStartedResponse{}
	mi := &file_workflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowExecutionStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowExecutionStartedResponse) ProtoMessage() {}

func (x *RecordWorkflowExecutionStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowExecutionStartedResponse.ProtoReflect.Descriptor instead.
func (*RecordWorkflowExecutionStartedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{23}
}

func (x *RecordWorkflowExecutionStartedResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RecordWorkflowTaskStartedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowTaskStartedRequest) Reset() {
	*x = RecordWorkflowTaskStartedRequest{}
	mi := &file_workflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowTaskStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowTaskStartedRequest) ProtoMessage() {}

func (x *RecordWorkflowTaskStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowTaskStartedRequest.ProtoReflect.Descriptor instead.
func (*RecordWorkflowTaskStartedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{24}
}

func (x *RecordWorkflowTaskStartedRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordWorkflowTaskStartedRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RecordWorkflowTaskStartedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowTaskStartedResponse) Reset() {
	*x = RecordWorkflowTaskStartedResponse{}
	mi := &file_workflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowTaskStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowTaskStartedResponse) ProtoMessage() {}

func (x *RecordWorkflowTaskStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowTaskStartedResponse.ProtoReflect.Descriptor instead.
func (*RecordWorkflowTaskStartedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{25}
}

type RecordWorkflowTaskCompletedHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Commands      []*Command             `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowTaskCompletedHistoryRequest) Reset() {
	*x = RecordWorkflowTaskCompletedHistoryRequest{}
	mi := &file_workflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowTaskCompletedHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowTaskCompletedHistoryRequest) ProtoMessage() {}

func (x *RecordWorkflowTaskCompletedHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowTaskCompletedHistoryRequest.ProtoReflect.Descriptor instead.
func (*RecordWorkflowTaskCompletedHistoryRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{26}
}

func (x *RecordWorkflowTaskCompletedHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordWorkflowTaskCompletedHistoryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordWorkflowTaskCompletedHistoryRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RecordWorkflowTaskCompletedHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowTaskCompletedHistoryResponse) Reset() {
	*x = RecordWorkflowTaskCompletedHistoryResponse{}
	mi := &file_workflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowTaskCompletedHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowTaskCompletedHistoryResponse) ProtoMessage() {}

func (x *RecordWorkflowTaskCompletedHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowTaskCompletedHistoryResponse.ProtoReflect.Descriptor instead.
func (*RecordWorkflowTaskCompletedHistoryResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{27}
}

type RecordActivityTaskStartedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskStartedRequest) Reset() {
	*x = RecordActivityTaskStartedRequest{}
	mi := &file_workflow_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskStartedRequest) ProtoMessage() {}

func (x *RecordActivityTaskStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskStartedRequest.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskStartedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{28}
}

func (x *RecordActivityTaskStartedRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordActivityTaskStartedRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordActivityTaskStartedRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type RecordActivityTaskStartedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskStartedResponse) Reset() {
	*x = RecordActivityTaskStartedResponse{}
	mi := &file_workflow_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskStartedResponse) ProtoMessage() {}

func (x *RecordActivityTaskStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskStartedResponse.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskStartedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{29}
}

type RecordActivityTaskCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskCompletedRequest) Reset() {
	*x = RecordActivityTaskCompletedRequest{}
	mi := &file_workflow_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskCompletedRequest) ProtoMessage() {}

func (x *RecordActivityTaskCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskCompletedRequest.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskCompletedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{30}
}

func (x *RecordActivityTaskCompletedRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordActivityTaskCompletedRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordActivityTaskCompletedRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *RecordActivityTaskCompletedRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type RecordActivityTaskCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskCompletedResponse) Reset() {
	*x = RecordActivityTaskCompletedResponse{}
	mi := &file_workflow_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskCompletedResponse) ProtoMessage() {}

func (x *RecordActivityTaskCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskCompletedResponse.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskCompletedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{31}
}

type RecordActivityTaskFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActivityId    string                 `protobuf:"bytes,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskFailedRequest) Reset() {
	*x = RecordActivityTaskFailedRequest{}
	mi := &file_workflow_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskFailedRequest) ProtoMessage() {}

func (x *RecordActivityTaskFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskFailedRequest.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskFailedRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{32}
}

func (x *RecordActivityTaskFailedRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordActivityTaskFailedRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordActivityTaskFailedRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *RecordActivityTaskFailedRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RecordActivityTaskFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityTaskFailedResponse) Reset() {
	*x = RecordActivityTaskFailedResponse{}
	mi := &file_workflow_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityTaskFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityTaskFailedResponse) ProtoMessage() {}

func (x *RecordActivityTaskFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityTaskFailedResponse.ProtoReflect.Descriptor instead.
func (*RecordActivityTaskFailedResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{33}
}

type AddWorkflowTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskQueue     string                 `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,4,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkflowTaskRequest) Reset() {
	*x = AddWorkflowTaskRequest{}
	mi := &file_workflow_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkflowTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkflowTaskRequest) ProtoMessage() {}

func (x *AddWorkflowTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkflowTaskRequest.ProtoReflect.Descriptor instead.
func (*AddWorkflowTaskRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{34}
}

func (x *AddWorkflowTaskRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *AddWorkflowTaskRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AddWorkflowTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AddWorkflowTaskRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

type AddWorkflowTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkflowTaskResponse) Reset() {
	*x = AddWorkflowTaskResponse{}
	mi := &file_workflow_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkflowTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkflowTaskResponse) ProtoMessage() {}

func (x *AddWorkflowTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkflowTaskResponse.ProtoReflect.Descriptor instead.
func (*AddWorkflowTaskResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{35}
}

type AddActivityTaskRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TaskQueue               string                 `protobuf:"bytes,1,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	WorkflowId              string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId                   string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ActivityId              string                 `protobuf:"bytes,4,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityType            string                 `protobuf:"bytes,5,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	Input                   []byte                 `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	HeartbeatTimeoutSeconds int32                  `protobuf:"varint,7,opt,name=heartbeat_timeout_seconds,json=heartbeatTimeoutSeconds,proto3" json:"heartbeat_timeout_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AddActivityTaskRequest) Reset() {
	*x = AddActivityTaskRequest{}
	mi := &file_workflow_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActivityTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActivityTaskRequest) ProtoMessage() {}

func (x *AddActivityTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActivityTaskRequest.ProtoReflect.Descriptor instead.
func (*AddActivityTaskRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{36}
}

func (x *AddActivityTaskRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *AddActivityTaskRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *AddActivityTaskRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AddActivityTaskRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *AddActivityTaskRequest) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *AddActivityTaskRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *AddActivityTaskRequest) GetHeartbeatTimeoutSeconds() int32 {
	if x != nil {
		return x.HeartbeatTimeoutSeconds
	}
	return 0
}

type AddActivityTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddActivityTaskResponse) Reset() {
	*x = AddActivityTaskResponse{}
	mi := &file_workflow_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActivityTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActivityTaskResponse) ProtoMessage() {}

func (x *AddActivityTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActivityTaskResponse.ProtoReflect.Descriptor instead.
func (*AddActivityTaskResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{37}
}

// Data Structures
type HistoryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g., "WorkflowExecutionStarted", "ActivityTaskScheduled"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEvent) Reset() {
	*x = HistoryEvent{}
	mi := &file_workflow_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEvent) ProtoMessage() {}

func (x *HistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEvent.ProtoReflect.Descriptor instead.
func (*HistoryEvent) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{38}
}

func (x *HistoryEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *HistoryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HistoryEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HistoryEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   string                 `protobuf:"bytes,1,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // e.g., "ScheduleActivityTask", "StartTimer", "CompleteWorkflowExecution"
	Attributes    []byte                 `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`                      // JSON-serialized attributes for the specific command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_workflow_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{39}
}

func (x *Command) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *Command) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type RecordWorkflowTaskFailedHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Cause         string                 `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowTaskFailedHistoryRequest) Reset() {
	*x = RecordWorkflowTaskFailedHistoryRequest{}
	mi := &file_workflow_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowTaskFailedHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowTaskFailedHistoryRequest) ProtoMessage() {}

func (x *RecordWorkflowTaskFailedHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowTaskFailedHistoryRequest.ProtoReflect.Descriptor instead.
func (*RecordWorkflowTaskFailedHistoryRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{40}
}

func (x *RecordWorkflowTaskFailedHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordWorkflowTaskFailedHistoryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordWorkflowTaskFailedHistoryRequest) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type RecordWorkflowTaskFailedHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowTaskFailedHistoryResponse) Reset() {
	*x = RecordWorkflowTaskFailedHistoryResponse{}
	mi := &file_workflow_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowTaskFailedHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowTaskFailedHistoryResponse) ProtoMessage() {}

func (x *RecordWorkflowTaskFailedHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowTaskFailedHistoryResponse.ProtoReflect.Descriptor instead.
func (*RecordWorkflowTaskFailedHistoryResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{41}
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\bworkflow\"\x91\x01\n" +
	"\x14StartWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x03 \x01(\tR\ttaskQueue\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\".\n" +
	"\x15StartWorkflowResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x86\x01\n" +
	"\x15SignalWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1f\n" +
	"\vsignal_name\x18\x04 \x01(\tR\n" +
	"signalName\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\"\x18\n" +
	"\x16SignalWorkflowResponse\"\x8c\x01\n" +
	"\x14QueryWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"query_type\x18\x03 \x01(\tR\tqueryType\x12\x1d\n" +
	"\n" +
	"query_args\x18\x04 \x01(\fR\tqueryArgs\":\n" +
	"\x15QueryWorkflowResponse\x12!\n" +
	"\fquery_result\x18\x01 \x01(\fR\vqueryResult\"K\n" +
	"\x11GetHistoryRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"F\n" +
	"\x12GetHistoryResponse\x120\n" +
	"\ahistory\x18\x01 \x03(\v2\x16.workflow.HistoryEventR\ahistory\"Y\n" +
	"\x1cPollWorkflowTaskQueueRequest\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x01 \x01(\tR\ttaskQueue\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\"\x95\x01\n" +
	"\x1dPollWorkflowTaskQueueResponse\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x120\n" +
	"\ahistory\x18\x03 \x03(\v2\x16.workflow.HistoryEventR\ahistory\"Y\n" +
	"\x1cPollActivityTaskQueueRequest\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x01 \x01(\tR\ttaskQueue\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\"\xd6\x01\n" +
	"\x1dPollActivityTaskQueueResponse\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\ractivity_type\x18\x03 \x01(\tR\factivityType\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\x12:\n" +
	"\x19heartbeat_timeout_seconds\x18\x05 \x01(\x05R\x17heartbeatTimeoutSeconds\"\x8f\x01\n" +
	"#RespondWorkflowTaskCompletedRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12-\n" +
	"\bcommands\x18\x02 \x03(\v2\x11.workflow.CommandR\bcommands\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\"&\n" +
	"$RespondWorkflowTaskCompletedResponse\"s\n" +
	" RespondWorkflowTaskFailedRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\"#\n" +
	"!RespondWorkflowTaskFailedResponse\"x\n" +
	"#RespondActivityTaskCompletedRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\"&\n" +
	"$RespondActivityTaskCompletedResponse\"\x8f\x01\n" +
	" RespondActivityTaskFailedRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1a\n" +
	"\bidentity\x18\x04 \x01(\tR\bidentity\"#\n" +
	"!RespondActivityTaskFailedResponse\"]\n" +
	"\"RecordActivityTaskHeartbeatRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12\x18\n" +
	"\adetails\x18\x02 \x01(\fR\adetails\"P\n" +
	"#RecordActivityTaskHeartbeatResponse\x12)\n" +
	"\x10cancel_requested\x18\x01 \x01(\bR\x0fcancelRequested\"l\n" +
	"%RecordWorkflowExecutionStartedRequest\x12C\n" +
	"\rstart_request\x18\x01 \x01(\v2\x1e.workflow.StartWorkflowRequestR\fstartRequest\"?\n" +
	"&RecordWorkflowExecutionStartedResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"Z\n" +
	" RecordWorkflowTaskStartedRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"#\n" +
	"!RecordWorkflowTaskStartedResponse\"\x92\x01\n" +
	")RecordWorkflowTaskCompletedHistoryRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12-\n" +
	"\bcommands\x18\x03 \x03(\v2\x11.workflow.CommandR\bcommands\",\n" +
	"*RecordWorkflowTaskCompletedHistoryResponse\"{\n" +
	" RecordActivityTaskStartedRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\tR\n" +
	"activityId\"#\n" +
	"!RecordActivityTaskStartedResponse\"\x95\x01\n" +
	"\"RecordActivityTaskCompletedRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\tR\n" +
	"activityId\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\"%\n" +
	"#RecordActivityTaskCompletedResponse\"\x92\x01\n" +
	"\x1fRecordActivityTaskFailedRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vactivity_id\x18\x03 \x01(\tR\n" +
	"activityId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\"\n" +
	" RecordActivityTaskFailedResponse\"\x94\x01\n" +
	"\x16AddWorkflowTaskRequest\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x01 \x01(\tR\ttaskQueue\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_type\x18\x04 \x01(\tR\fworkflowType\"\x19\n" +
	"\x17AddWorkflowTaskResponse\"\x87\x02\n" +
	"\x16AddActivityTaskRequest\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x01 \x01(\tR\ttaskQueue\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1f\n" +
	"\vactivity_id\x18\x04 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\ractivity_type\x18\x05 \x01(\tR\factivityType\x12\x14\n" +
	"\x05input\x18\x06 \x01(\fR\x05input\x12:\n" +
	"\x19heartbeat_timeout_seconds\x18\a \x01(\x05R\x17heartbeatTimeoutSeconds\"\x19\n" +
	"\x17AddActivityTaskResponse\"\x80\x01\n" +
	"\fHistoryEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"L\n" +
	"\aCommand\x12!\n" +
	"\fcommand_type\x18\x01 \x01(\tR\vcommandType\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x01(\fR\n" +
	"attributes\"v\n" +
	"&RecordWorkflowTaskFailedHistoryRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\")\n" +
	"'RecordWorkflowTaskFailedHistoryResponse2\x9e\t\n" +
	"\x0fFrontendService\x12P\n" +
	"\rStartWorkflow\x12\x1e.workflow.StartWorkflowRequest\x1a\x1f.workflow.StartWorkflowResponse\x12S\n" +
	"\x0eSignalWorkflow\x12\x1f.workflow.SignalWorkflowRequest\x1a .workflow.SignalWorkflowResponse\x12P\n" +
	"\rQueryWorkflow\x12\x1e.workflow.QueryWorkflowRequest\x1a\x1f.workflow.QueryWorkflowResponse\x12X\n" +
	"\x1bGetWorkflowExecutionHistory\x12\x1b.workflow.GetHistoryRequest\x1a\x1c.workflow.GetHistoryResponse\x12h\n" +
	"\x15PollWorkflowTaskQueue\x12&.workflow.PollWorkflowTaskQueueRequest\x1a'.workflow.PollWorkflowTaskQueueResponse\x12}\n" +
	"\x1cRespondWorkflowTaskCompleted\x12-.workflow.RespondWorkflowTaskCompletedRequest\x1a..workflow.RespondWorkflowTaskCompletedResponse\x12t\n" +
	"\x19RespondWorkflowTaskFailed\x12*.workflow.RespondWorkflowTaskFailedRequest\x1a+.workflow.RespondWorkflowTaskFailedResponse\x12h\n" +
	"\x15PollActivityTaskQueue\x12&.workflow.PollActivityTaskQueueRequest\x1a'.workflow.PollActivityTaskQueueResponse\x12}\n" +
	"\x1cRespondActivityTaskCompleted\x12-.workflow.RespondActivityTaskCompletedRequest\x1a..workflow.RespondActivityTaskCompletedResponse\x12t\n" +
	"\x19RespondActivityTaskFailed\x12*.workflow.RespondActivityTaskFailedRequest\x1a+.workflow.RespondActivityTaskFailedResponse\x12z\n" +
	"\x1bRecordActivityTaskHeartbeat\x12,.workflow.RecordActivityTaskHeartbeatRequest\x1a-.workflow.RecordActivityTaskHeartbeatResponse2\x8c\n" +
	"\n" +
	"\x0eHistoryService\x12\x83\x01\n" +
	"\x1eRecordWorkflowExecutionStarted\x12/.workflow.RecordWorkflowExecutionStartedRequest\x1a0.workflow.RecordWorkflowExecutionStartedResponse\x12t\n" +
	"\x19RecordWorkflowTaskStarted\x12*.workflow.RecordWorkflowTaskStartedRequest\x1a+.workflow.RecordWorkflowTaskStartedResponse\x12\x88\x01\n" +
	"\x1bRecordWorkflowTaskCompleted\x123.workflow.RecordWorkflowTaskCompletedHistoryRequest\x1a4.workflow.RecordWorkflowTaskCompletedHistoryResponse\x12\x7f\n" +
	"\x18RecordWorkflowTaskFailed\x120.workflow.RecordWorkflowTaskFailedHistoryRequest\x1a1.workflow.RecordWorkflowTaskFailedHistoryResponse\x12t\n" +
	"\x19RecordActivityTaskStarted\x12*.workflow.RecordActivityTaskStartedRequest\x1a+.workflow.RecordActivityTaskStartedResponse\x12z\n" +
	"\x1bRecordActivityTaskCompleted\x12,.workflow.RecordActivityTaskCompletedRequest\x1a-.workflow.RecordActivityTaskCompletedResponse\x12q\n" +
	"\x18RecordActivityTaskFailed\x12).workflow.RecordActivityTaskFailedRequest\x1a*.workflow.RecordActivityTaskFailedResponse\x12z\n" +
	"\x1bRecordActivityTaskHeartbeat\x12,.workflow.RecordActivityTaskHeartbeatRequest\x1a-.workflow.RecordActivityTaskHeartbeatResponse\x12\\\n" +
	"\x17SignalWorkflowExecution\x12\x1f.workflow.SignalWorkflowRequest\x1a .workflow.SignalWorkflowResponse\x12Y\n" +
	"\x16QueryWorkflowExecution\x12\x1e.workflow.QueryWorkflowRequest\x1a\x1f.workflow.QueryWorkflowResponse\x12X\n" +
	"\x1bGetWorkflowExecutionHistory\x12\x1b.workflow.GetHistoryRequest\x1a\x1c.workflow.GetHistoryResponse2\x95\x03\n" +
	"\x0fMatchingService\x12V\n" +
	"\x0fAddWorkflowTask\x12 .workflow.AddWorkflowTaskRequest\x1a!.workflow.AddWorkflowTaskResponse\x12V\n" +
	"\x0fAddActivityTask\x12 .workflow.AddActivityTaskRequest\x1a!.workflow.AddActivityTaskResponse\x12h\n" +
	"\x15PollWorkflowTaskQueue\x12&.workflow.PollWorkflowTaskQueueRequest\x1a'.workflow.PollWorkflowTaskQueueResponse\x12h\n" +
	"\x15PollActivityTaskQueue\x12&.workflow.PollActivityTaskQueueRequest\x1a'.workflow.PollActivityTaskQueueResponseB\x1cZ\x1amini-workflow/api;workflowb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_workflow_proto_goTypes = []any{
	(*StartWorkflowRequest)(nil),                       // 0: workflow.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),                      // 1: workflow.StartWorkflowResponse
	(*SignalWorkflowRequest)(nil),                      // 2: workflow.SignalWorkflowRequest
	(*SignalWorkflowResponse)(nil),                     // 3: workflow.SignalWorkflowResponse
	(*QueryWorkflowRequest)(nil),                       // 4: workflow.QueryWorkflowRequest
	(*QueryWorkflowResponse)(nil),                      // 5: workflow.QueryWorkflowResponse
	(*GetHistoryRequest)(nil),                          // 6: workflow.GetHistoryRequest
	(*GetHistoryResponse)(nil),                         // 7: workflow.GetHistoryResponse
	(*PollWorkflowTaskQueueRequest)(nil),               // 8: workflow.PollWorkflowTaskQueueRequest
	(*PollWorkflowTaskQueueResponse)(nil),              // 9: workflow.PollWorkflowTaskQueueResponse
	(*PollActivityTaskQueueRequest)(nil),               // 10: workflow.PollActivityTaskQueueRequest
	(*PollActivityTaskQueueResponse)(nil),              // 11: workflow.PollActivityTaskQueueResponse
	(*RespondWorkflowTaskCompletedRequest)(nil),        // 12: workflow.RespondWorkflowTaskCompletedRequest
	(*RespondWorkflowTaskCompletedResponse)(nil),       // 13: workflow.RespondWorkflowTaskCompletedResponse
	(*RespondWorkflowTaskFailedRequest)(nil),           // 14: workflow.RespondWorkflowTaskFailedRequest
	(*RespondWorkflowTaskFailedResponse)(nil),          // 15: workflow.RespondWorkflowTaskFailedResponse
	(*RespondActivityTaskCompletedRequest)(nil),        // 16: workflow.RespondActivityTaskCompletedRequest
	(*RespondActivityTaskCompletedResponse)(nil),       // 17: workflow.RespondActivityTaskCompletedResponse
	(*RespondActivityTaskFailedRequest)(nil),           // 18: workflow.RespondActivityTaskFailedRequest
	(*RespondActivityTaskFailedResponse)(nil),          // 19: workflow.RespondActivityTaskFailedResponse
	(*RecordActivityTaskHeartbeatRequest)(nil),         // 20: workflow.RecordActivityTaskHeartbeatRequest
	(*RecordActivityTaskHeartbeatResponse)(nil),        // 21: workflow.RecordActivityTaskHeartbeatResponse
	(*RecordWorkflowExecutionStartedRequest)(nil),      // 22: workflow.RecordWorkflowExecutionStartedRequest
	(*RecordWorkflowExecutionStartedResponse)(nil),     // 23: workflow.RecordWorkflowExecutionStartedResponse
	(*RecordWorkflowTaskStartedRequest)(nil),           // 24: workflow.RecordWorkflowTaskStartedRequest
	(*RecordWorkflowTaskStartedResponse)(nil),          // 25: workflow.RecordWorkflowTaskStartedResponse
	(*RecordWorkflowTaskCompletedHistoryRequest)(nil),  // 26: workflow.RecordWorkflowTaskCompletedHistoryRequest
	(*RecordWorkflowTaskCompletedHistoryResponse)(nil), // 27: workflow.RecordWorkflowTaskCompletedHistoryResponse
	(*RecordActivityTaskStartedRequest)(nil),           // 28: workflow.RecordActivityTaskStartedRequest
	(*RecordActivityTaskStartedResponse)(nil),          // 29: workflow.RecordActivityTaskStartedResponse
	(*RecordActivityTaskCompletedRequest)(nil),         // 30: workflow.RecordActivityTaskCompletedRequest
	(*RecordActivityTaskCompletedResponse)(nil),        // 31: workflow.RecordActivityTaskCompletedResponse
	(*RecordActivityTaskFailedRequest)(nil),            // 32: workflow.RecordActivityTaskFailedRequest
	(*RecordActivityTaskFailedResponse)(nil),           // 33: workflow.RecordActivityTaskFailedResponse
	(*AddWorkflowTaskRequest)(nil),                     // 34: workflow.AddWorkflowTaskRequest
	(*AddWorkflowTaskResponse)(nil),                    // 35: workflow.AddWorkflowTaskResponse
	(*AddActivityTaskRequest)(nil),                     // 36: workflow.AddActivityTaskRequest
	(*AddActivityTaskResponse)(nil),                    // 37: workflow.AddActivityTaskResponse
	(*HistoryEvent)(nil),                               // 38: workflow.HistoryEvent
	(*Command)(nil),                                    // 39: workflow.Command
	(*RecordWorkflowTaskFailedHistoryRequest)(nil),     // 40: workflow.RecordWorkflowTaskFailedHistoryRequest
	(*RecordWorkflowTaskFailedHistoryResponse)(nil),    // 41: workflow.RecordWorkflowTaskFailedHistoryResponse
}
var file_workflow_proto_depIdxs = []int32{
	38, // 0: workflow.GetHistoryResponse.history:type_name -> workflow.HistoryEvent
	38, // 1: workflow.PollWorkflowTaskQueueResponse.history:type_name -> workflow.HistoryEvent
	39, // 2: workflow.RespondWorkflowTaskCompletedRequest.commands:type_name -> workflow.Command
	0,  // 3: workflow.RecordWorkflowExecutionStartedRequest.start_request:type_name -> workflow.StartWorkflowRequest
	39, // 4: workflow.RecordWorkflowTaskCompletedHistoryRequest.commands:type_name -> workflow.Command
	0,  // 5: workflow.FrontendService.StartWorkflow:input_type -> workflow.StartWorkflowRequest
	2,  // 6: workflow.FrontendService.SignalWorkflow:input_type -> workflow.SignalWorkflowRequest
	4,  // 7: workflow.FrontendService.QueryWorkflow:input_type -> workflow.QueryWorkflowRequest
	6,  // 8: workflow.FrontendService.GetWorkflowExecutionHistory:input_type -> workflow.GetHistoryRequest
	8,  // 9: workflow.FrontendService.PollWorkflowTaskQueue:input_type -> workflow.PollWorkflowTaskQueueRequest
	12, // 10: workflow.FrontendService.RespondWorkflowTaskCompleted:input_type -> workflow.RespondWorkflowTaskCompletedRequest
	14, // 11: workflow.FrontendService.RespondWorkflowTaskFailed:input_type -> workflow.RespondWorkflowTaskFailedRequest
	10, // 12: workflow.FrontendService.PollActivityTaskQueue:input_type -> workflow.PollActivityTaskQueueRequest
	16, // 13: workflow.FrontendService.RespondActivityTaskCompleted:input_type -> workflow.RespondActivityTaskCompletedRequest
	18, // 14: workflow.FrontendService.RespondActivityTaskFailed:input_type -> workflow.RespondActivityTaskFailedRequest
	20, // 15: workflow.FrontendService.RecordActivityTaskHeartbeat:input_type -> workflow.RecordActivityTaskHeartbeatRequest
	22, // 16: workflow.HistoryService.RecordWorkflowExecutionStarted:input_type -> workflow.RecordWorkflowExecutionStartedRequest
	24, // 17: workflow.HistoryService.RecordWorkflowTaskStarted:input_type -> workflow.RecordWorkflowTaskStartedRequest
	26, // 18: workflow.HistoryService.RecordWorkflowTaskCompleted:input_type -> workflow.RecordWorkflowTaskCompletedHistoryRequest
	40, // 19: workflow.HistoryService.RecordWorkflowTaskFailed:input_type -> workflow.RecordWorkflowTaskFailedHistoryRequest
	28, // 20: workflow.HistoryService.RecordActivityTaskStarted:input_type -> workflow.RecordActivityTaskStartedRequest
	30, // 21: workflow.HistoryService.RecordActivityTaskCompleted:input_type -> workflow.RecordActivityTaskCompletedRequest
	32, // 22: workflow.HistoryService.RecordActivityTaskFailed:input_type -> workflow.RecordActivityTaskFailedRequest
	20, // 23: workflow.HistoryService.RecordActivityTaskHeartbeat:input_type -> workflow.RecordActivityTaskHeartbeatRequest
	2,  // 24: workflow.HistoryService.SignalWorkflowExecution:input_type -> workflow.SignalWorkflowRequest
	4,  // 25: workflow.HistoryService.QueryWorkflowExecution:input_type -> workflow.QueryWorkflowRequest
	6,  // 26: workflow.HistoryService.GetWorkflowExecutionHistory:input_type -> workflow.GetHistoryRequest
	34, // 27: workflow.MatchingService.AddWorkflowTask:input_type -> workflow.AddWorkflowTaskRequest
	36, // 28: workflow.MatchingService.AddActivityTask:input_type -> workflow.AddActivityTaskRequest
	8,  // 29: workflow.MatchingService.PollWorkflowTaskQueue:input_type -> workflow.PollWorkflowTaskQueueRequest
	10, // 30: workflow.MatchingService.PollActivityTaskQueue:input_type -> workflow.PollActivityTaskQueueRequest
	1,  // 31: workflow.FrontendService.StartWorkflow:output_type -> workflow.StartWorkflowResponse
	3,  // 32: workflow.FrontendService.SignalWorkflow:output_type -> workflow.SignalWorkflowResponse
	5,  // 33: workflow.FrontendService.QueryWorkflow:output_type -> workflow.QueryWorkflowResponse
	7,  // 34: workflow.FrontendService.GetWorkflowExecutionHistory:output_type -> workflow.GetHistoryResponse
	9,  // 35: workflow.FrontendService.PollWorkflowTaskQueue:output_type -> workflow.PollWorkflowTaskQueueResponse
	13, // 36: workflow.FrontendService.RespondWorkflowTaskCompleted:output_type -> workflow.RespondWorkflowTaskCompletedResponse
	15, // 37: workflow.FrontendService.RespondWorkflowTaskFailed:output_type -> workflow.RespondWorkflowTaskFailedResponse
	11, // 38: workflow.FrontendService.PollActivityTaskQueue:output_type -> workflow.PollActivityTaskQueueResponse
	17, // 39: workflow.FrontendService.RespondActivityTaskCompleted:output_type -> workflow.RespondActivityTaskCompletedResponse
	19, // 40: workflow.FrontendService.RespondActivityTaskFailed:output_type -> workflow.RespondActivityTaskFailedResponse
	21, // 41: workflow.FrontendService.RecordActivityTaskHeartbeat:output_type -> workflow.RecordActivityTaskHeartbeatResponse
	23, // 42: workflow.HistoryService.RecordWorkflowExecutionStarted:output_type -> workflow.RecordWorkflowExecutionStartedResponse
	25, // 43: workflow.HistoryService.RecordWorkflowTaskStarted:output_type -> workflow.RecordWorkflowTaskStartedResponse
	27, // 44: workflow.HistoryService.RecordWorkflowTaskCompleted:output_type -> workflow.RecordWorkflowTaskCompletedHistoryResponse
	41, // 45: workflow.HistoryService.RecordWorkflowTaskFailed:output_type -> workflow.RecordWorkflowTaskFailedHistoryResponse
	29, // 46: workflow.HistoryService.RecordActivityTaskStarted:output_type -> workflow.RecordActivityTaskStartedResponse
	31, // 47: workflow.HistoryService.RecordActivityTaskCompleted:output_type -> workflow.RecordActivityTaskCompletedResponse
	33, // 48: workflow.HistoryService.RecordActivityTaskFailed:output_type -> workflow.RecordActivityTaskFailedResponse
	21, // 49: workflow.HistoryService.RecordActivityTaskHeartbeat:output_type -> workflow.RecordActivityTaskHeartbeatResponse
	3,  // 50: workflow.HistoryService.SignalWorkflowExecution:output_type -> workflow.SignalWorkflowResponse
	5,  // 51: workflow.HistoryService.QueryWorkflowExecution:output_type -> workflow.QueryWorkflowResponse
	7,  // 52: workflow.HistoryService.GetWorkflowExecutionHistory:output_type -> workflow.GetHistoryResponse
	35, // 53: workflow.MatchingService.AddWorkflowTask:output_type -> workflow.AddWorkflowTaskResponse
	37, // 54: workflow.MatchingService.AddActivityTask:output_type -> workflow.AddActivityTaskResponse
	9,  // 55: workflow.MatchingService.PollWorkflowTaskQueue:output_type -> workflow.PollWorkflowTaskQueueResponse
	11, // 56: workflow.MatchingService.PollActivityTaskQueue:output_type -> workflow.PollActivityTaskQueueResponse
	31, // [31:57] is the sub-list for method output_type
	5,  // [5:31] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
